# Generated by Django 3.2.9 on 2022-01-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(blank=True, max_length=255, null=True)),
                ('blok', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penyakit', models.CharField(blank=True, max_length=255, null=True)),
                ('bab_penyakit', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_penyakit', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_penyakit', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
