# Generated by Django 3.2.9 on 2022-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0002_klasifikasi_penyakit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm',
            name='kode_diagnosis',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
