# Generated by Django 3.2.9 on 2022-01-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perhitungan', '0004_auto_20220118_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='perhitungan',
            name='iteration',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
