# Generated by Django 3.2.9 on 2022-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perhitungan', '0005_perhitungan_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perhitungan',
            name='iteration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
